In [10]:
import tensorflow as tf
import tensorflow.data as td

import numpy as np

In [11]:
sl_num = [23, 22, 32, -43, -1, 52, 23, 12, 32, -9, 0, 22]

In [26]:
tf_data = tf.data.Dataset.from_tensor_slices(sl_num)
for sl in tf_data.as_numpy_iterator():
    print(sl)

23
22
32
-43
-1
52
23
12
32
-9
0
22


In [34]:
tf_data1 = tf_data.filter(lambda x: x>0)
for sl in tf_data1:
    print(sl.numpy())

23
22
32
52
23
12
32
22


In [37]:
tf_data2 = tf_data1.map(lambda x: x*100)
for sl in tf_data2:
    print(sl.numpy())

2300
2200
3200
5200
2300
1200
3200
2200


In [38]:
tf_data3 = tf_data2.shuffle(4)
for sl in tf_data3:
    print(sl.numpy())

5200
2300
1200
3200
3200
2300
2200
2200


In [43]:
tf_data3 = tf_data2.batch(5)
for sl in tf_data3:
    print(sl.numpy())

[2300 2200 3200 5200 2300]
[1200 3200 2200]


# All in one line

In [ ]:
sl_num = [23, 22, 32, -43, -1, 52, 23, 12, 32, -9, 0, 22]

In [47]:
data = tf.data.Dataset.from_tensor_slices(sl_num).filter(lambda x: x>0).map(lambda y: y*100).shuffle(4).batch(5)

for sl in data.as_numpy_iterator():
    print(sl)

[2300 2300 3200 1200 2200]
[2200 3200 5200]


In [ ]:

#input X_train
#import plt and standardscaler

def plots(df, var, t):
    plt.figure(figsize=(13,5))
    plt.subplot(121)
    sns.kdeplot(df[var])
    plt.title('before ' + str(t).split('(')[0])
    
    plt.subplot(122)
    p1 = t.fit_transform(df[[var]]).flatten()
    sns.kdeplot(p1)
    plt.title('after ' + str(t).split('(')[0])
    

    
for col in X_train.columns:
    plots(X_train, col, StandardScaler())